version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  app:
    build: ./app
    volumes:
      - ./app:/app   # <--- mount folder host ke container
    container_name: ollama-client
    depends_on:
      - ollama
    environment:
      - MODEL_NAME=mistral
    stdin_open: true  # supaya bisa attach
    tty: true         # supaya terminal interaktif
    restart: unless-stopped

volumes:
  ollama_data:
