version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama  # simpan model di host biar ga download ulang

  app:
    build: ./app
    container_name: ollama-client
    depends_on:
      - ollama
    environment:
      - MODEL_NAME=mistral
    stdin_open: true
    tty: true

volumes:
  ollama_data:
